version: '3'

services:
  lab1:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "8000"
    ports:
      - "8000:8000"
    container_name: lab1
